### ISSUE TITLE
detection.txt not found

### ISSUE THREAD

**Issue by TungWg** [layer6ai-labs/SGG-Seq2Seq#6]
Hi, when I run preprocess_evaluation.py, 'data/detection.txt' can't be found, how can I get this file? thanks!

**Comment by YichaoLu** [comment]
You can download pre-trained object detection models [https://drive.google.com/file/d/1NrqOLbMa_RwHbG3KIXJFWLnlND2kiIpj/view](url) and run inference to get the detection files.

**Comment by Git-oNmE** [comment]
> You can download pre-trained object detection models [https://drive.google.com/file/d/1NrqOLbMa_RwHbG3KIXJFWLnlND2kiIpj/view](url) and run inference to get the detection files.

Sorry, but what you mean by "run inference" ? I haven't fount a script named "inference" in the project or in the file that the link  
directed to download. 
I still cannot get the detection.txt file.

Your reply will be appreciated, thanks.
